# Generated by Django 4.0.3 on 2023-04-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_homecontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='home_images/'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='message_image',
            field=models.ImageField(blank=True, null=True, upload_to='home_images/'),
        ),
    ]
