# Generated by Django 4.0.3 on 2023-04-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_homecontent_intro_image_homecontent_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='no_of_students',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homecontent',
            name='no_of_teachers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homecontent',
            name='since',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homecontent',
            name='success_rate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
