# Generated by Django 4.1.4 on 2023-04-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_homecontent_no_of_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.CharField(max_length=200)),
                ('mini_title_text', models.CharField(max_length=150)),
                ('title_text', models.CharField(max_length=150)),
                ('sub_text', models.TextField()),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='home_images/')),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
            ],
            options={
                'verbose_name_plural': '11.About Page Content',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=150)),
                ('team', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_images/')),
            ],
            options={
                'verbose_name_plural': '10. team',
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blogs_images/', verbose_name='Image (670*670)'),
        ),
    ]
