# Generated by Django 4.1.4 on 2023-04-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_aboutcontent_team_delete_message_alter_blog_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardMember',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='linkedin',
        ),
    ]
