# Generated by Django 4.1.4 on 2023-04-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
    ]
