# Generated by Django 4.1.4 on 2023-04-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
