# Generated by Django 4.1.4 on 2023-04-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_team_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images', verbose_name='Image (800*500)')),
                ('heading_text', models.CharField(max_length=200)),
                ('sub_heading_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '10. Slider',
            },
        ),
        migrations.RemoveField(
            model_name='schoolsetup',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='schoolsetup',
            name='map_url',
        ),
    ]
