# Generated by Django 4.2 on 2023-04-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_slider_remove_schoolsetup_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='sub_text',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='title_text',
        ),
    ]
