# Generated by Django 4.1.4 on 2023-04-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_slider_remove_schoolsetup_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('notice', 'notice'), ('event', 'event')], max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': '09. Notice',
            },
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='sub_text',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='title_text',
        ),
    ]
