# Generated by Django 4.1.4 on 2023-04-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0012_notice_remove_homecontent_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(default='sdadasdsadsa', max_length=255),
            preserve_default=False,
        ),
    ]
