# Generated by Django 3.2 on 2023-05-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0013_notice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
